import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fef3ff",
        "on-secondary-fixed": "#4d137b",
        "primary": "#702ae1",
        "on-secondary": "#fbefff",
        "surface-dim": "#e8c9ff",
        "secondary-container": "#e6c5ff",
        "surface-container-high": "#f1daff",
        "on-primary": "#f8f0ff",
        "on-primary-fixed-variant": "#390083",
        "secondary-fixed": "#e6c5ff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#9e3657",
        "primary-dim": "#6411d5",
        "error": "#b41340",
        "on-surface-variant": "#69537b",
        "tertiary-fixed-dim": "#f77c9e",
        "tertiary-dim": "#8e294c",
        "tertiary-container": "#ff8eac",
        "surface-container-highest": "#edd3ff",
        "surface-variant": "#edd3ff",
        "on-secondary-container": "#612c90",
        "secondary": "#7742a6",
        "surface": "#fef3ff",
        "on-error-container": "#510017",
        "inverse-on-surface": "#ad93c0",
        "on-primary-fixed": "#000000",
        "surface-tint": "#702ae1",
        "primary-container": "#b28cff",
        "outline": "#856e98",
        "on-tertiary-fixed": "#380016",
        "secondary-dim": "#6a3599",
        "primary-fixed": "#b28cff",
        "on-background": "#3a264b",
        "on-tertiary-container": "#64042d",
        "on-secondary-fixed-variant": "#6b369a",
        "on-tertiary": "#ffeff1",
        "on-tertiary-fixed-variant": "#711036",
        "on-surface": "#3a264b",
        "secondary-fixed-dim": "#ddb3ff",
        "surface-container": "#f5e2ff",
        "tertiary-fixed": "#ff8eac",
        "primary-fixed-dim": "#a67aff",
        "on-error": "#ffefef",
        "background": "#fef3ff",
        "inverse-primary": "#a476ff",
        "error-container": "#f74b6d",
        "outline-variant": "#bda3d1",
        "on-primary-container": "#2e006c",
        "inverse-surface": "#180429",
        "error-dim": "#a70138",
        "surface-container-low": "#faecff"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Plus Jakarta Sans'", "sans-serif"],
        "label": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
} satisfies Config;
